#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  default:
    - step:
        script:
          - pip install pandas
          - pip install telegram
          - python -m doctest -v script/main.py
          - echo "Everything is awesome"
      #     name: Test
      #     caches:
      #       - pip
      #     script:
      #       - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      #       - pip install pytest
      #       - pytest -v tests/* --junitxml=test-reports/report.xml
      # - step:
      #     name: Lint code
      #     script:
      #       # Enforce style consistency across Python projects https://flake8.pycqa.org/en/latest/manpage.html
      #       - pip install flake8
      #       - flake8 . --extend-exclude=dist,build --show-source --statistics
